services:
  - type: web
    name: family-smart-saver-backend
    env: node
    rootDir: FamilyFinanceTracker/
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    # Removed: ports field is not directly supported here, Render auto-detects
    autoDeploy: true
    # free tier will spin down with inactivity
    # instanceType: free

  - type: web
    name: family-smart-saver-frontend
    runtime: static
    rootDir: FamilyFinanceTracker/client/
    buildCommand: npm install && npm run build
    staticPublishPath: dist # Corrected: changed to staticPublishPath
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        fromService: 
          type: web
          name: family-smart-saver-backend
          property: host
          
