services:
  - type: web
    name: family-smart-saver-backend
    env: node
    rootDir: FamilyFinanceTracker/
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    ports: 
      - 5000
    autoDeploy: true
    # free tier will spin down with inactivity
    # instanceType: free

  - type: static
    name: family-smart-saver-frontend
    env: node
    rootDir: FamilyFinanceTracker/client/
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        fromService: 
          type: web
          name: family-smart-saver-backend
          property: host
          
